# Generated by Django 4.1.2 on 2022-10-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='create',
            new_name='created',
        ),
    ]
